# site settings
title: Home of the Flow
subtitle: by Avigyle Zeitchik
email: gyle@yogigyle.com
description: Yoga is an experiential science.<br /> Practice it. Live it. Breathe it.
baseurl: # (Was "/welcome") the subpath of your site, e.g. /blog
url: https://yogigyle.com # (Was empty) the base hostname & protocol for your site
author:
street_address: Tel Aviv, Israel
city: 
state: 
zip_code: 
country: 
phone: (+972) 58-786-8422

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram: https://instagram.com/yogigyle
  LinkedIn: https://www.linkedin.com/in/avigyle-zeitchik-a48455b0
  Twitter:
  Facebook: https://facebook.com/yogigyle
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 

# Staticman v2 comments (using GitHub account as bot)
# staticman_url: https://yogigyle-staticman.onrender.com/v2/entry/yogigyle/yogigyle.github.io/master/comments

# Staticman v3 comments (using GitHub App)
staticman_url: https://yogigyle-staticman.onrender.com/v3/entry/github/yogigyle/yogigyle.github.io/master/comments
enableComments: true

#reCAPTCHA v2:
reCaptcha:
  siteKey: "6LcLGtYZAAAAAMLmWSGriudVk_R7lwkmJI9ztQvV"
  secret: "lkxAl9krCLy4UUcdvMSn3TrBYT8y1xe8uLlb005UbpDcA4uVWGQ1H1PhtLTI32zhLK+U90Pz/AyXkFwAGg1Bc3pmwT+JaEzHBCINECu8mxlUc4gzJato8P2Eyp+XpucygwPLTfUmNAtMJNRrVRYNmEKYkTWz9UXEnMk02vAMkuZiGV3/cetTUy0tDoS+Cg0WN4At9qqjHORYAbGjNObMeAtOnhAXJKQeSr4y1GTmXc3yXN7iddQTx9NII9RPc/R1QeAEYj0yjZ4N4Q8kXKHM+C4FRIYxdcaUmlmil5cmMIvGfZyunrp7n8rHchdp/slDpIQq6/e4fosJZaZd8JTIW2sTxkaG3GqJ1DMay66i2vbd1Vd37K+9s9tFTdjMf1Ra32QUp4fPO/fMHvnTMOdR9vOf6/X9UsoiC+8uNlsyj7A3dhTPKp8SzQVyDKniyRfW2u153aIqNlNFHqUvw+jShSfRsCGKDhFQQE+Bts63NArQ7SnIxin9nDFMwAtF+AgSi1eeWLSOysvzfTcl+oVEcaqCSaIVF2+/E5nmSiigHqNyeoJ+IOqZDiktqJs+HJBeC2mYFmKAK/9+RBKu0UBsv7/z+CV6c6ZEoOmz2+3GCtAyunXMT7JXmVHwavnm4ZRolh2s4rqHBuwMHaR5ahjr91QnLurtRf/OB82Ffq1YLKI="

# [Aviram 2021-05-21] Organizing all .md webpages in a designated folder "_pages", adding below lines to load it properly in Jekyll:
include:
  - _pages

# [Aviram 2023-02-03] Removing the date from posts URL and prepending "elements" to the blog post filename:
# BEFORE: https://yogigyle.com/2021/01/30/vayus.html
# AFTER: http://yogigyle.com/elements/vayus/
permalink: /elements/:title/

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:basename/
